-- Decoration Settings

-- Sourcing colors generated by matugen (InioX/matugen-themes)
-- NOTE: the new template returns a Lua table instead of setting bare
-- globals, so this is now `local colors = require(...)` and every
-- reference below is `colors.<role>` instead of a bare `colorN`.
local colors = require("matugen/colors-hyprland")

hl.config({
  general = {
    border_size = 0,
    gaps_in = 0,
    gaps_out = 0,
    
    col = {
      --active_border = colors.tertiary_container,
      --inactive_border = colors.primary,
      active_border = colors.primary,
      inactive_border = "rgba(0,0,0,0)",
    }
  },

  decoration = {
    rounding = 0,
          
    active_opacity = 1.0,
    inactive_opacity = 0.9,
    fullscreen_opacity = 1.0,

    dim_inactive = true,
    dim_strength = 0.1,
    dim_special = 0.8,

    shadow = {
      enabled = true,
      range = 10,
      render_power = 5,

      --color = colors.tertiary_container
      --color_inactive = colors.primary
      color = colors.primary,
      color_inactive = "rgba(0,0,0,0)",
    },

    blur = {
      enabled = true,	
      size = 6,
      passes = 2,
      ignore_opacity = false,
      new_optimizations = true,
      special = true,
      popups = true,
    },
  },
})