-- Decoration Settings

-- Sourcing colors generated by wallust
require("matugen/colors-hyprland")

hl.config({
  general = {
    border_size = 0,
    gaps_in = 0,
    gaps_out = 0,
    
    col = {
      --active_border = color10,
      --inactive_border = color12,
      active_border = color12,
      inactive_border = "rgba(0,0,0,0)",
    }
  },

  decoration = {
    rounding = 0,
          
    active_opacity = 1.0,
    inactive_opacity = 0.9,
    fullscreen_opacity = 1.0,

    dim_inactive = true,
    dim_strength = 0.1,
    dim_special = 0.8,

    shadow = {
      enabled = true,
      range = 10,
      render_power = 5,

      --color = color10
      --color_inactive = color12
      color = color12,
      color_inactive = "rgba(0,0,0,0)",
    },

    blur = {
      enabled = true,	
      size = 6,
      passes = 2,
      ignore_opacity = false,
      new_optimizations = true,
      special = true,
      popups = true,
    },
  },
})