-- Generated by nwg-displays on 2026-06-27 at 16:02:03. Do not edit manually.

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x515@60.0",
    position = "3840x565",
    scale = 1.0
})
hl.monitor({
    output = "DP-2",
    mode = "3840x1080@144.0",
    position = "0x0",
    scale = 1.0
})
