-- Generated by nwg-displays on 2026-06-27 at 16:02:03. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "DP-2",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "DP-2"
})
hl.workspace_rule({
    workspace = "3",
    monitor = "DP-2"
})
hl.workspace_rule({
    workspace = "4",
    monitor = "DP-2"
})
hl.workspace_rule({
    workspace = "5",
    monitor = "DP-2"
})
hl.workspace_rule({
    workspace = "6",
    monitor = "DP-2"
})
hl.workspace_rule({
    workspace = "7",
    monitor = "DP-2"
})
hl.workspace_rule({
    workspace = "8",
    monitor = "DP-2"
})
hl.workspace_rule({
    workspace = "9",
    monitor = "DP-2"
})
hl.workspace_rule({
    workspace = "10",
    monitor = "DP-2"
})
hl.workspace_rule({
    workspace = "11",
    monitor = "DP-2"
})
hl.workspace_rule({
    workspace = "12",
    monitor = "DP-2"
})
hl.workspace_rule({
    workspace = "13",
    monitor = "DP-2"
})
hl.workspace_rule({
    workspace = "14",
    monitor = "DP-2"
})
hl.workspace_rule({
    workspace = "15",
    monitor = "DP-2"
})
hl.workspace_rule({
    workspace = "16",
    monitor = "DP-2"
})
hl.workspace_rule({
    workspace = "17",
    monitor = "DP-2"
})
hl.workspace_rule({
    workspace = "18",
    monitor = "DP-2"
})
hl.workspace_rule({
    workspace = "19",
    monitor = "DP-2"
})
hl.workspace_rule({
    workspace = "20",
    monitor = "HDMI-A-1",
    default = true
})
