# matugen template - colors-kitty

foreground         {{colors.on_background.default.hex}}
background         {{colors.background.default.hex}}
cursor             {{colors.primary.default.hex}}

active_tab_foreground     {{colors.background.default.hex}}
active_tab_background     {{colors.on_background.default.hex}}
inactive_tab_foreground   {{colors.on_background.default.hex}}
inactive_tab_background   {{colors.background.default.hex}}

active_border_color   {{colors.primary.default.hex}}
inactive_border_color {{colors.outline_variant.default.hex}}
bell_border_color     {{colors.error.default.hex}}

color0  {{palettes.neutral._10.hex}}
color1  {{colors.error.default.hex}}
color2  {{colors.tertiary.default.hex}}
color3  {{palettes.secondary._70.hex}}
color4  {{colors.primary.default.hex}}
color5  {{palettes.tertiary._60.hex}}
color6  {{palettes.secondary._60.hex}}
color7  {{palettes.neutral._80.hex}}
color8  {{palettes.neutral._30.hex}}
color9  {{palettes.error._70.hex}}
color10 {{palettes.tertiary._80.hex}}
color11 {{colors.secondary.default.hex}}
color12 {{palettes.primary._70.hex}}
color13 {{palettes.tertiary._80.hex}}
color14 {{palettes.secondary._80.hex}}
color15 {{palettes.neutral._95.hex}}
